app/generator/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^add/$', views.add, name='add'),
]

config/urls.py
from django.views.decorators.clickjacking import xframe_options_exempt
from django.conf.urls import url, static
from django.urls import include, path
from django.views.static import serve
from rest_framework import routers
from django.conf import settings
from django.contrib import admin

from generator.apis import (
    GeneratorViewSet,
    TaskViewSet,
)
from generator.views import (
    get_latest_palika_pdf,
    download_export_as_zip,
)

# Rest Routers
router = routers.DefaultRouter()

router.register(r'generators', GeneratorViewSet, basename='generator')
router.register(r'tasks', TaskViewSet, basename='task')

# Versioning : (v1|v2|v3)
API_PREFIX = r'^api/(?P<version>(v1))/'


def get_api_path(path):
    return '{}{}'.format(API_PREFIX, path)


urlpatterns = [
    # Admin url patterns
    path('admin/', admin.site.urls),

    # Recent palika document
    url(
        r'^recent-palika-document/(?P<palika_code>\d+)/(?P<language>\w+)/$',
        get_latest_palika_pdf,
        name='recent-palika-document',
    ),
    url(
        r'^download-palika-documents/$',
        download_export_as_zip,
        name='recent-palika-document',
    ),

    # API url patterns
    url(get_api_path(''), include(router.urls)),

    # App url patterns
    url(r'^generators/', include(
        ('generator.urls', 'generator'),
        namespace='generator'),
        ),

] + static.static(
    settings.MEDIA_URL, view=xframe_options_exempt(serve),
    document_root=settings.MEDIA_ROOT
)

app/generator/models.py
import os

from django.db import models
from django.contrib.postgres.fields import JSONField

from geo.models import GeoStyleFile


class TaskModel(models.Model):
    NOT_PROCESSED = 'not_processed'
    PENDING = 'pending'
    SUCCESS = 'success'
    FAILURE = 'failure'

    STATUSES = (
        (NOT_PROCESSED, 'Not Processed'),
        (PENDING, 'Pending'),
        (SUCCESS, 'Success'),
        (FAILURE, 'Failure'),
    )

    status = models.CharField(
        max_length=30, choices=STATUSES, default=NOT_PROCESSED,
    )

    class Meta:
        abstract = True
        ordering = ['-created_at']


class Generator(TaskModel):
    file = models.FileField(upload_to='documents/', max_length=255)
    errors = JSONField(default=dict, null=True, blank=True)
    data = JSONField(default=dict, null=True, blank=True)
    geo_meta = JSONField(default=dict, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial_file = self.file

    def __str__(self):
        return os.path.splitext(os.path.basename(self.file.name))[0]


class Export(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    file = models.FileField(upload_to='exports/', max_length=255)
    palika_code = models.CharField(max_length=255, null=True, blank=True)
    language = models.CharField(
        max_length=30, choices=GeoStyleFile.LANGUAGE_CHOICES, default=GeoStyleFile.ENGLISH,
    )
    generator = models.ForeignKey(
        Generator,
        on_delete=models.CASCADE,
        related_name='exports',
    )

    def __str__(self):
        return os.path.splitext(os.path.basename(self.file.name))[0]

app/generator/views.py
from io import BytesIO
from zipfile import ZipFile

from django.http import (
    FileResponse,
    Http404,
    HttpResponse,
    HttpResponseBadRequest,
)
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from geo.models import GeoStyleFile
from .models import Export


@login_required()
def list(request):
    return render(request, 'generator/list.html')


@login_required()
def add(request):
    return render(request, 'generator/add.html')


def get_latest_palika_pdf(request, palika_code, language=GeoStyleFile.ENGLISH):
    export = Export.objects.filter(
        palika_code=palika_code,
        language=language,
    ).order_by('-pk').first()
    if export:
        response = FileResponse(export.file)
        return response
    raise Http404('Document not found for {}'.format(palika_code))


@login_required()
def download_export_as_zip(request):
    generator_id = request.GET.get('generatorId')
    exports_id = request.GET.get('exportsId', '')
    if generator_id:
        exports = Export.objects.filter(generator=generator_id)
    elif exports_id:
        exports = Export.objects.filter(
            pk__in=[int(x) for x in exports_id.split(',')],
        )
    else:
        return HttpResponseBadRequest('Either provide generatorId or exportsId')

    mem = BytesIO()
    zip = ZipFile(mem, 'a')
    for i, export in enumerate(exports.all()):
        zip.writestr(
            export.title or 'Document-{}.pdf'.format(i),
            export.file.read(),
        )
    for file in zip.filelist:
        file.create_system = 0
    zip.close()
    response = HttpResponse(content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=download.zip'
    mem.seek(0)
    response.write(mem.read())
    return response

app/templates/generator/add.html
{% extends "react_plugins_base.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'generator:list' %}">{% trans 'List Generators' %}</a>
        &rsaquo; Add Generators
        {% block breadcrumb %}{% endblock %}
    </div>
{% endblock %}

{% block content %}
    <div id="generator-add"></div>

    {% load react_serve %}
    <script type="text/javascript" src="{% react_serve 'react-plugins.js' %}"></script>
    <script>
        let messageNo = 1;
        reactPlugins.render(
            'GeneratorAdd',
            '#generator-add',
        );
    </script>
{% endblock %}

app/templates/generator/list.html
{% extends "react_plugins_base.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; List Generators
        {% block breadcrumb %}{% endblock %}
    </div>
{% endblock %}

{% block content %}
    <div id="generator-list"></div>

    {% load react_serve %}
    <script type="text/javascript" src="{% react_serve 'react-plugins.js' %}"></script>
    <script>
        let messageNo = 1;
        reactPlugins.render(
            'Generators',
            '#generator-list',
            {
                'addGeneratorPageUrl': '{% url 'generator:add' %}',
            }
        );
    </script>
{% endblock %}